spring:
  application:
    name: order
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: password
      database: web
      port: 27017
      host: localhost
  config:
    import: "optional:configserver:http://localhost:8088"

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'