server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: user
        uri: lb://customer
        predicates[0]: Path=/user
        predicates[1]: Method=GET
      routes[1]:
        id: order
        uri: lb://order
        predicates[0]: Path=/order
        predicates[1]: Method=GET

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'

management:
  tracing:
    sampling:
      probability: 1.0