server:
  port: 8085

spring:
  application:
    name: order
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: password
      database: web
      port: 27017
      host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
#  level:
#    org.mongodb.driver: DEBUG